export default {
  SERVER: 'SERVER',
  LANGAGE: 'LANGAGE',
  THEME: 'THEME',
  USER_INFO: 'USER_INFO',
  TIMEOUT_CONNECT: 'TIMEOUT_CONNECT',
  EXPIRE_SESSION: 'EXPIRE_SESSION',
  APP_LOGIN_ID: 'APP_LOGIN_ID',
};
